# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq texlive
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh
    - sudo sh lilypond-2.18.2-1.linux-64.sh --batch

matrix:
  include:
   - r: release
     after_success:
       - Rscript -e 'covr::codecov(function_exclusions = "\\.onLoad$", line_exclusions = list("R/tabr.R" = c(151:155, 167), "R/snippet.R" = 388:390, "R/lp_render.R" = c(104, 109, 267, 272), "R/midi.R" = c(85, 166, 171, 231:232), "R/utils.R" = c(18, 26)))'
   - r: devel
     r_build_args: --no-build-vignettes
     r_check_args: --ignore-vignettes --no-examples
   - r: oldrel
     r_build_args: --no-build-vignettes
     r_check_args: --ignore-vignettes --no-examples
